#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker978"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6e3d5632f4a54f33966a819434c6c3fb" }
]

[assets]
directory = "./public"
